# -*- coding: utf-8 -*-
"""Another copy of gai-project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VoZ_J58Z9Mc26MX6rKkEg0qc_OzPMlgk
"""

import tensorflow as tf
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

import requests
from io import BytesIO

# URLs of the content and style images
content_image_url = "https://th.bing.com/th/id/OIP.1d6tBbNiJTFQNEK_k0sSjQHaFj?rs=1&pid=ImgDetMain"
style_image_url = "https://i.pinimg.com/736x/49/15/7d/49157d3d99418b298e134cd809674283.jpg"

# Function to load image from URL
def load_image_from_url(url):
    response = requests.get(url)
    img = Image.open(BytesIO(response.content))
    return img

# Load content and style images
content_image = load_image_from_url(content_image_url)
style_image = load_image_from_url(style_image_url)

# Display the images (optional)
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.imshow(content_image)
plt.title('Content Image')
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(style_image)
plt.title('Style Image')
plt.axis('off')

plt.show()

def preprocess_image(image):
    img = image.resize((224, 224))  # Resize to match VGG19 input size
    img = np.array(img)
    img = np.expand_dims(img, axis=0)  # Add batch dimension
    img = tf.keras.applications.vgg19.preprocess_input(img)  # Preprocess for VGG19
    return img

# Preprocess content and style images
content_image = preprocess_image(content_image)
style_image = preprocess_image(style_image)

# Load VGG19 model without the top (fully connected layers)
vgg19 = tf.keras.applications.VGG19(include_top=False, weights='imagenet')
vgg19.trainable = False  # Freeze VGG19 weights

# Define layers for content and style representations
content_layers = ['block5_conv2']
style_layers = [
    'block1_conv1',
    'block2_conv1',
    'block3_conv1',
    'block4_conv1',
    'block5_conv1'
]

# Outputs for content and style layers
content_outputs = [vgg19.get_layer(name).output for name in content_layers]
style_outputs = [vgg19.get_layer(name).output for name in style_layers]

# Model to extract content and style features
extractor_model = tf.keras.Model(inputs=vgg19.input, outputs=content_outputs + style_outputs)

# Function to compute content and style representations
def compute_features(image, model):
    features = model(image)
    content_features = features[:len(content_layers)]
    style_features = features[len(content_layers):]
    return content_features, style_features

# Compute content and style features for content and style images
content_features, style_features = compute_features(content_image, extractor_model)
style_features_orig = style_features  # Save original style features for later use

# Function to compute content loss
def content_loss(content, target):
    return tf.reduce_mean(tf.square(content - target))

# Function to compute gram matrix (used for style loss)
def gram_matrix(input_tensor):
    result = tf.linalg.einsum('bijc,bijd->bcd', input_tensor, input_tensor)
    input_shape = tf.shape(input_tensor)
    num_locations = tf.cast(input_shape[1] * input_shape[2], tf.float32)
    return result / num_locations

# Function to compute style loss
def style_loss(style, target):
    style_gram = gram_matrix(style)
    target_gram = gram_matrix(target)
    return tf.reduce_mean(tf.square(style_gram - target_gram))

# Weight factors for content and style loss
alpha = 1e3  # Content weight
beta = 1e-2  # Style weight

# Function to compute total loss
def total_loss(outputs, content_targets, style_targets):
    content_outputs = outputs[:len(content_layers)]
    style_outputs = outputs[len(content_layers):]

    content_loss_value = 0.0
    style_loss_value = 0.0

    # Compute content loss
    for content, target in zip(content_outputs, content_targets):
        content_loss_value += content_loss(content, target)

    # Compute style loss
    for style, target in zip(style_outputs, style_targets):
        style_loss_value += style_loss(style, target)

    total_loss = alpha * content_loss_value + beta * style_loss_value
    return total_loss

# Compute content and style targets
content_targets = compute_features(content_image, extractor_model)[0]
style_targets = compute_features(style_image, extractor_model)[1:]

# Compute content and style targets
content_targets = compute_features(content_image, extractor_model)[0]
style_targets = [tf.convert_to_tensor(t) for t in compute_features(style_image, extractor_model)[1]] # Convert list elements to tensors

# Initialize generated image with content image
generated_image = tf.Variable(content_image)

# Function to compute gradients
def compute_gradients(image):
    with tf.GradientTape() as tape:
        outputs = extractor_model(image)
        loss = total_loss(outputs, content_targets, style_targets)
    gradients = tape.gradient(loss, image)
    return loss, gradients

# Optimizer parameters
optimizer = tf.optimizers.Adam(learning_rate=5.0, beta_1=0.99, epsilon=1e-1)

# Number of iterations for optimization
iterations = 150
iterations = 100

# Optimization loop
for i in range(iterations):
    loss, gradients = compute_gradients(generated_image)
    optimizer.apply_gradients([(gradients, generated_image)])

    if i % 100 == 0:
        print(f"Iteration {i}: Total loss: {loss}")

# generated image
generated_image = np.clip(generated_image.numpy().squeeze(), 0, 255).astype(np.uint8)

# Display
plt.figure(figsize=(8, 8))
plt.imshow(generated_image)
plt.title('Generated Image with Style Transfer')
plt.axis('off')
plt.show()

!pip install torch transformers diffusers

from diffusers import StableDiffusionPipeline
import torch
# Load the Stable Diffusion pipeline
model_id = "CompVis/stable-diffusion-v1-4"
device = "cuda" if torch.cuda.is_available() else "cpu"
pipeline = StableDiffusionPipeline.from_pretrained(model_id, use_auth_token=True)
pipeline.to(device)
def generate_stable_diffusion_image(prompt):
    # Generate image
    image = pipeline(prompt).images[0]
    return image
# Example usage
prompt = "A beautiful sunset over the mountains"
generated_image = generate_stable_diffusion_image(prompt)
# Save or display the image
generated_image.save("stable_diffusion_generated_image.png")

from IPython.display import Image
Image('stable_diffusion_generated_image.png')

import torch
import torch.optim as optim
from torch import nn
from torchvision import transforms, models
from PIL import Image
import matplotlib.pyplot as plt

# Load the images
def load_image(img_path, max_size=400, shape=None):
    """Loads and scales image to max_size"""
    img = Image.open(img_path)
    if max_size:
        size = max(max(img.size), max_size)
        img = img.resize((size, int(size * img.size[1] / img.size[0])), Image.LANCZOS)
    if shape:
        img = img.resize(shape, Image.LANCZOS)
    return img

# Preprocessing images for the model
def preprocess_image(image):
    """Preprocess image to tensor for feeding to the model"""
    transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ])
    image = transform(image).unsqueeze(0)
    return image

# Postprocessing the output image
def postprocess_image(tensor):
    """Converts tensor back to a usable image"""
    tensor = tensor.squeeze(0)
    tensor = tensor.detach().cpu()
    unloader = transforms.ToPILImage()
    image = unloader(tensor)
    return image

# Load content and style images
content_path = '/content/context.jpeg'
style_path = '/content/style.jpeg'

content_image = load_image(content_path).convert('RGB')
style_image = load_image(style_path, shape=content_image.size).convert('RGB')

# Display images
plt.figure()
plt.imshow(content_image)
plt.title("Content Image")
plt.show()

plt.figure()
plt.imshow(style_image)
plt.title("Style Image")
plt.show()

# Preprocess images for model
content_tensor = preprocess_image(content_image).to(torch.device("cuda" if torch.cuda.is_available() else "cpu"))
style_tensor = preprocess_image(style_image).to(torch.device("cuda" if torch.cuda.is_available() else "cpu"))

# Load the pre-trained VGG19 model
vgg = models.vgg19(pretrained=True).features.to(torch.device("cuda" if torch.cuda.is_available() else "cpu")).eval()

# Layers used for style and content extraction
def get_features(image, model, layers=None):
    """Extracts features from the specified layers"""
    if layers is None:
        layers = {
            '0': 'conv1_1', '5': 'conv2_1', '10': 'conv3_1', '19': 'conv4_1', '21': 'conv4_2', '28': 'conv5_1'
        }

    features = {}
    x = image
    for name, layer in model._modules.items():
        x = layer(x)
        if name in layers:
            features[layers[name]] = x
    return features

# Extract content and style features
content_features = get_features(content_tensor, vgg)
style_features = get_features(style_tensor, vgg)

# Initialize the target image (copy of the content image)
target_tensor = content_tensor.clone().requires_grad_(True)

# Set up optimizer for target image
optimizer = optim.Adam([target_tensor], lr=0.003)

# Define the loss functions
def gram_matrix(tensor):
    """Compute the Gram matrix of the feature map"""
    _, d, h, w = tensor.size()
    tensor = tensor.view(d, h * w)
    gram = torch.mm(tensor, tensor.t())
    return gram

def compute_loss(target_features, content_features, style_features, content_weight=1e3, style_weight=1e-2):
    """Compute total loss"""
    content_loss = torch.mean((target_features['conv4_2'] - content_features['conv4_2'])**2)
    style_loss = 0
    for layer in style_features:
        target_gram = gram_matrix(target_features[layer])
        style_gram = gram_matrix(style_features[layer])
        style_loss += torch.mean((target_gram - style_gram)**2)

    total_loss = content_weight * content_loss + style_weight * style_loss
    return total_loss, content_loss, style_loss

# Run the optimization process (training loop)
epochs = 500
for epoch in range(epochs):
    optimizer.zero_grad()

    # Extract features of the target image
    target_features = get_features(target_tensor, vgg)

    # Compute the loss
    total_loss, content_loss, style_loss = compute_loss(target_features, content_features, style_features)

    # Backpropagate and optimize the target image
    total_loss.backward(retain_graph=True) # Add retain_graph=True here
    optimizer.step()

    # Print progress every 50 steps
    if epoch % 50 == 0:
        print(f"Epoch [{epoch}/{epochs}] - Total Loss: {total_loss.item()}")

# Display the final output image
output_image = postprocess_image(target_tensor)
plt.imshow(output_image)
plt.title("Generated Image")
plt.show()

import torch
import torch.optim as optim
from torch import nn
from torchvision import transforms, models
from PIL import Image
import matplotlib.pyplot as plt

# Load images
def load_image(img_path, max_size=400, shape=None):
    """Loads and scales image to max_size"""
    img = Image.open(img_path).convert("RGB")
    if max_size:
        size = max(img.size) if max(img.size) < max_size else max_size
        img = img.resize((size, int(size * img.size[1] / img.size[0])), Image.LANCZOS)
    if shape:
        img = img.resize(shape, Image.LANCZOS)
    return img

# Preprocessing images for model input
def preprocess_image(image):
    """Preprocess image to tensor for model"""
    transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ])
    image = transform(image).unsqueeze(0)
    return image

# Post-processing the output image
def postprocess_image(tensor):
    """Convert tensor back to an image"""
    tensor = tensor.squeeze(0).detach().cpu()
    tensor = torch.clamp(tensor, 0, 1)  # Ensure values are between 0 and 1
    unloader = transforms.ToPILImage()
    return unloader(tensor)

# Paths to images
content_path = "/content/download.png"
style_path = "/content/download(2).png"

# Load content and style images
content_image = load_image(content_path)
style_image = load_image(style_path, shape=content_image.size)

# Display images
plt.figure()
plt.imshow(content_image)
plt.title("Content Image")
plt.show()

plt.figure()
plt.imshow(style_image)
plt.title("Style Image")
plt.show()

# Set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Convert images to tensors
content_tensor = preprocess_image(content_image).to(device)
style_tensor = preprocess_image(style_image).to(device)

# Load the pre-trained VGG19 model
vgg = models.vgg19(weights=models.VGG19_Weights.DEFAULT).features.to(device).eval()

# Define feature extraction function
def get_features(image, model, layers=None):
    """Extracts features from specific layers"""
    if layers is None:
        layers = {
            '0': 'conv1_1', '5': 'conv2_1', '10': 'conv3_1',
            '19': 'conv4_1', '21': 'conv4_2', '28': 'conv5_1'
        }

    features = {}
    x = image
    for name, layer in model._modules.items():
        x = layer(x)
        if name in layers:
            features[layers[name]] = x
    return features

# Extract features from content and style images
content_features = get_features(content_tensor, vgg)
style_features = get_features(style_tensor, vgg)

# Initialize target image (copy of content image)
target_tensor = content_tensor.clone().requires_grad_(True)

# Set up optimizer for the target image
optimizer = optim.Adam([target_tensor], lr=0.001)  # Lowered LR for stable updates

# Compute Gram Matrix for style representation
def gram_matrix(tensor):
    """Compute the Gram matrix of the feature map"""
    _, d, h, w = tensor.size()
    tensor = tensor.view(d, h * w)
    gram = torch.mm(tensor, tensor.t())
    return gram / (d * h * w)  # Normalize

# Compute content and style loss
def compute_loss(target_features, content_features, style_features, content_weight=1e4, style_weight=1e-3):
    """Compute total loss (content + style)"""
    content_loss = torch.mean((target_features['conv4_2'] - content_features['conv4_2'])**2)

    style_loss = 0
    for layer in style_features:
        target_gram = gram_matrix(target_features[layer])
        style_gram = gram_matrix(style_features[layer])
        style_loss += torch.mean((target_gram - style_gram)**2)

    total_loss = content_weight * content_loss + style_weight * style_loss
    return total_loss, content_loss, style_loss

# Training loop for style transfer
epochs = 500
for epoch in range(epochs):
    optimizer.zero_grad()

    # Extract target image features
    target_features = get_features(target_tensor, vgg)

    # Compute loss
    total_loss, content_loss, style_loss = compute_loss(target_features, content_features, style_features)

    # Backpropagation
    total_loss.backward(retain_graph=True)
    optimizer.step()

    # Print progress every 50 iterations
    if epoch % 50 == 0:
        print(f"Epoch [{epoch}/{epochs}] - Total Loss: {total_loss.item():.4f}, Content Loss: {content_loss.item():.4f}, Style Loss: {style_loss.item():.4f}")

# Post-process and display the final image
target_tensor.data.clamp_(0, 1)  # Ensure values are in [0,1]
output_image = postprocess_image(target_tensor)

plt.imshow(output_image)
plt.title("Generated Image")
plt.show()

# Save the final output image
output_image.save("/content/stylized_output.jpeg")
print("Stylized image saved as 'stylized_output.jpeg'.")